### ISSUE TITLE
NameError in line 24 of /SalmonTE-master/snakemake/Snakefile.paired: name 'directory' is not defined

### ISSUE THREAD

**Issue by Gemma-Zhang-326** [hyunhwan-jeong/SalmonTE#67]
Hi I am trying to use SalmonTE, but encounter an issue when testing with the example data. Could help me check this? Many thanks!

(SalmonTE) SalmonTE-master$ python SalmonTE.py quant --reference=hs  ./example
2022-05-17 10:23:58,042 Starting quantification mode
2022-05-17 10:23:58,042 Collecting FASTQ files...
2022-05-17 10:23:58,042 SalmonTE assumes that './example/' is a directory, and SalmonTE will search any FASTQ file in the directory.
2022-05-17 10:23:58,043 The input dataset is considered as a paired-ends dataset.
2022-05-17 10:23:58,044 Collected 4 FASTQ files.
2022-05-17 10:23:58,044 Quantification has been finished.
2022-05-17 10:23:58,044 Running Salmon using Snakemake
NameError in line 24 of /SalmonTE-master/snakemake/Snakefile.paired:
name 'directory' is not defined
  File "/SalmonTE-master/snakemake/Snakefile.paired", line 24, in <module>
2022-05-17 10:23:58,124 NameError in line 24 of /SalmonTE-master/snakemake/Snakefile.paired:
name 'directory' is not defined
  File "/Salmon/SalmonTE-master/snakemake/Snakefile.paired", line 24, in <module>
Traceback (most recent call last):
  File "SalmonTE.py", line 292, in <module>
    run(args)
  File "SalmonTE.py", line 243, in run
    run_salmon(param)
  File "SalmonTE.py", line 156, in run_salmon
    with open(os.path.join(param["--outpath"], "EXPR.csv" ), "r") as inp:
FileNotFoundError: [Errno 2] No such file or directory: '/Salmon/SalmonTE-master/SalmonTE_output/EXPR.csv'

Gemma

**Comment by Gemma-Zhang-326** [comment]
I find out this bugs due to the version of snakemake is too old. The problem is solved when I update snakemake to 7.6.2 
Thank you!
