### ISSUE TITLE
job execution failed

### ISSUE THREAD

**Issue by sulevk** [hyunhwan-jeong/SalmonTE#70]
I tried salmonTE with another computer, macOS 12.4 and got a different error:

./salmonTE.py quant --reference=hs example
2022-06-19 12:47:02,064 Starting quantification mode
2022-06-19 12:47:02,064 Collecting FASTQ files...
2022-06-19 12:47:02,064 SalmonTE assumes that 'example' is a directory, and SalmonTE will search any FASTQ file in the directory.
2022-06-19 12:47:02,069 The input dataset is considered as a paired-ends dataset.
2022-06-19 12:47:02,069 Collected 4 FASTQ files.
2022-06-19 12:47:02,070 Quantification has been finished.
2022-06-19 12:47:02,070 Running Salmon using Snakemake
2022-06-19 12:47:02,310 Lock 140659507911888 acquired on /var/folders/q4/xbxmf14s385_x024mxmhcnf00000gn/T/tmp5v15ujcpsnakemake-runtime-source-cache/20f3d1092614679bad1b248387247a2fedd98c5753b9c4b5f357a4f5f3ed2ae0.lock
2022-06-19 12:47:02,311 Lock 140659507911888 released on /var/folders/q4/xbxmf14s385_x024mxmhcnf00000gn/T/tmp5v15ujcpsnakemake-runtime-source-cache/20f3d1092614679bad1b248387247a2fedd98c5753b9c4b5f357a4f5f3ed2ae0.lock
/Users/sulevkoks/Terminalis/SalmonTE/snakemake/Snakefile.paired:103: SyntaxWarning: "is" with a literal. Did you mean "=="?
Job stats:
job                    count    min threads    max threads
-------------------  -------  -------------  -------------
all                        1              1              1
collect_abundance          1              1              1
collect_mappability        1              1              1
run_salmon_fq              4              1              1
total                      7              1              1

2022-06-19 12:47:02,369 Job stats:
job                    count    min threads    max threads
-------------------  -------  -------------  -------------
all                        1              1              1
collect_abundance          1              1              1
collect_mappability        1              1              1
run_salmon_fq              4              1              1
total                      7              1              1

/bin/bash: line 1: 26559 Abort trap: 6           ./salmon/darwin/bin/salmon quant -q -i reference/hs -l A -1 /var/folders/q4/xbxmf14s385_x024mxmhcnf00000gn/T/tmp4_1pz6s_/TARDBP_2_R1.fastq -2 /var/folders/q4/xbxmf14s385_x024mxmhcnf00000gn/T/tmp4_1pz6s_/TARDBP_2_R2.fastq -o /Users/sulevkoks/Terminalis/SalmonTE/SalmonTE_output/TARDBP_2 -p 4 2> /dev/null
[Sun Jun 19 12:47:02 2022]
2022-06-19 12:47:02,462 [Sun Jun 19 12:47:02 2022]
Error in rule run_salmon_fq:
2022-06-19 12:47:02,462 Error in rule run_salmon_fq:
    jobid: 3
2022-06-19 12:47:02,462     jobid: 3
    output: /Users/sulevkoks/Terminalis/SalmonTE/SalmonTE_output/TARDBP_2
2022-06-19 12:47:02,462     output: /Users/sulevkoks/Terminalis/SalmonTE/SalmonTE_output/TARDBP_2
    shell:
        ./salmon/darwin/bin/salmon quant -q -i reference/hs -l A -1 /var/folders/q4/xbxmf14s385_x024mxmhcnf00000gn/T/tmp4_1pz6s_/TARDBP_2_R1.fastq -2 /var/folders/q4/xbxmf14s385_x024mxmhcnf00000gn/T/tmp4_1pz6s_/TARDBP_2_R2.fastq -o /Users/sulevkoks/Terminalis/SalmonTE/SalmonTE_output/TARDBP_2 -p 4 2>/dev/null
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
2022-06-19 12:47:02,463     shell:
        ./salmon/darwin/bin/salmon quant -q -i reference/hs -l A -1 /var/folders/q4/xbxmf14s385_x024mxmhcnf00000gn/T/tmp4_1pz6s_/TARDBP_2_R1.fastq -2 /var/folders/q4/xbxmf14s385_x024mxmhcnf00000gn/T/tmp4_1pz6s_/TARDBP_2_R2.fastq -o /Users/sulevkoks/Terminalis/SalmonTE/SalmonTE_output/TARDBP_2 -p 4 2>/dev/null
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

2022-06-19 12:47:02,463 
Exiting because a job execution failed. Look above for error message
2022-06-19 12:47:02,464 Exiting because a job execution failed. Look above for error message
Traceback (most recent call last):
  File "./salmonTE.py", line 292, in <module>
    run(args)
  File "./salmonTE.py", line 243, in run
    run_salmon(param)
  File "./salmonTE.py", line 156, in run_salmon
    with open(os.path.join(param["--outpath"], "EXPR.csv" ), "r") as inp:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/sulevkoks/Terminalis/SalmonTE/SalmonTE_output/EXPR.csv'

Any ideas about what's wrong?

**Comment by sulevk** [comment]
No, I haven't found anything.

**Comment by hyunhwan-jeong** [comment]
Hi @sulevk and @Chenoax3, 

This will require a build of salmon from its source, and not sure how easy it is. One workaround option would be using a virtual machine or docker. I probably can build a docker image for it, does it work?

Thank you,

Hyun-Hwan Jeong

**Comment by Chenoax3** [comment]
Hi @hyunhwan-jeong,

thanks for your help! I am not familiar with using virtual machines or docker, but it sounds easy to use. What do I have to do?

I could try running SalmonTE on another computer. Do you think it would make a difference? 

Best, 
Chenoa

**Comment by Meatpie996** [comment]
I had same problem in the conda environment in both Mac and WSL Ubuntu. It seems snakemake doesn’t work under that condition. You should try python venv. At least, it worked in WSL Ubuntu in my case.

**Comment by hyunhwan-jeong** [comment]
duplicate with #75 #74
